spring.application.name=StudentManagementSystem

spring.datasource.url=jdbc:mysql://localhost:3306/students_db
spring.datasource.username=root
spring.datasource.password=Arshad@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true